"""empty message

Revision ID: 7f0e3ae701ad
Revises: 
Create Date: 2019-01-10 11:37:24.075812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0e3ae701ad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('recorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location_description', sa.String(length=100), nullable=True),
    sa.Column('current_series_uid', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recorder_uid'), 'recorder', ['uid'], unique=True)
    op.create_table('recording_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('samplerate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Numeric(precision=13, scale=7, asdecimal=False), nullable=True),
    sa.Column('amplification', sa.Numeric(precision=10, scale=7, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parameters_uid', sa.String(length=36), nullable=True),
    sa.Column('recorder_uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parameters_uid'], ['recording_parameters.uid'], ),
    sa.ForeignKeyConstraint(['recorder_uid'], ['recorder.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Numeric(precision=17, scale=7, asdecimal=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('series_uid', sa.String(length=36), nullable=False),
    sa.Column('label_uid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['label_uid'], ['label.uid'], ),
    sa.ForeignKeyConstraint(['series_uid'], ['series.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    op.drop_table('series')
    op.drop_table('recording_parameters')
    op.drop_index(op.f('ix_recorder_uid'), table_name='recorder')
    op.drop_table('recorder')
    op.drop_table('label')
    # ### end Alembic commands ###
