"""empty message

Revision ID: f23bc955e6e0
Revises: 
Create Date: 2018-12-29 16:12:17.618323

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f23bc955e6e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('recorder',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('location_description', sa.String(length=100), nullable=True),
    sa.Column('current_series_uid', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recorder_uid'), 'recorder', ['uid'], unique=True)
    op.create_table('recording_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('samplerate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Numeric(precision=13, scale=7, asdecimal=False), nullable=True),
    sa.Column('amplification', sa.Numeric(precision=10, scale=7, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parameters_uid', sa.String(length=36), nullable=True),
    sa.Column('recorder_uid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parameters_uid'], ['recording_parameters.uid'], ),
    sa.ForeignKeyConstraint(['recorder_uid'], ['recorder.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.Numeric(precision=17, scale=7, asdecimal=False), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('series_uid', sa.String(length=36), nullable=False),
    sa.Column('label_uid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['label_uid'], ['label.uid'], ),
    sa.ForeignKeyConstraint(['series_uid'], ['series.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.drop_table('columns_priv')
    op.drop_table('plugin')
    op.drop_table('slave_relay_log_info')
    op.drop_table('event')
    op.drop_table('time_zone_transition')
    op.drop_table('gtid_executed')
    op.drop_table('func')
    op.drop_table('time_zone')
    op.drop_table('servers')
    op.drop_table('slave_worker_info')
    op.drop_table('innodb_index_stats')
    op.drop_table('proc')
    op.drop_table('time_zone_name')
    op.drop_table('slave_master_info')
    op.drop_table('procs_priv')
    op.drop_table('proxies_priv')
    op.drop_table('time_zone_leap_second')
    op.drop_table('user')
    op.drop_table('server_cost')
    op.drop_table('help_relation')
    op.drop_index('name', table_name='help_category')
    op.drop_table('help_category')
    op.drop_index('name', table_name='help_keyword')
    op.drop_table('help_keyword')
    op.drop_table('innodb_table_stats')
    op.drop_table('db')
    op.drop_table('general_log')
    op.drop_index('name', table_name='help_topic')
    op.drop_table('help_topic')
    op.drop_table('ndb_binlog_index')
    op.drop_table('time_zone_transition_type')
    op.drop_table('tables_priv')
    op.drop_table('engine_cost')
    op.drop_table('slow_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slow_log',
    sa.Column('start_time', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('query_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('lock_time', mysql.TIME(fsp=6), nullable=False),
    sa.Column('rows_sent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('rows_examined', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('db', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('last_insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('insert_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sql_text', mysql.MEDIUMBLOB(), nullable=False),
    sa.Column('thread_id', mysql.BIGINT(display_width=21, unsigned=True), autoincrement=False, nullable=False),
    mysql_comment='Slow log',
    mysql_default_charset='utf8',
    mysql_engine='CSV'
    )
    op.create_table('engine_cost',
    sa.Column('engine_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('device_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cost_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('cost_value', mysql.FLOAT(), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('cost_name', 'engine_name', 'device_type'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('tables_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=93), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Table_priv', mysql.SET(charset='utf8', length=11), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_priv', mysql.SET(charset='utf8', length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Table_name'),
    mysql_collate='utf8_bin',
    mysql_comment='Table privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('time_zone_transition_type',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Offset', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Is_DST', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Abbreviation', mysql.CHAR(length=8), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_type_id'),
    mysql_comment='Time zone transition types',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ndb_binlog_index',
    sa.Column('Position', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('File', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('epoch', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('inserts', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('updates', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('deletes', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('schemaops', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('orig_server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('orig_epoch', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('gci', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('next_position', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('next_file', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('epoch', 'orig_server_id', 'orig_epoch'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_table('help_topic',
    sa.Column('help_topic_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('help_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('example', mysql.TEXT(), nullable=False),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_topic_id'),
    mysql_comment='help topics',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'help_topic', ['name'], unique=True)
    op.create_table('general_log',
    sa.Column('event_time', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('user_host', mysql.MEDIUMTEXT(), nullable=False),
    sa.Column('thread_id', mysql.BIGINT(display_width=21, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('server_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('command_type', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('argument', mysql.MEDIUMBLOB(), nullable=False),
    mysql_comment='General log',
    mysql_default_charset='utf8',
    mysql_engine='CSV'
    )
    op.create_table('db',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User'),
    mysql_collate='utf8_bin',
    mysql_comment='Database privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('innodb_table_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8_bin', length=199), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('n_rows', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('clustered_index_size', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sum_of_other_index_sizes', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('help_keyword',
    sa.Column('help_keyword_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id'),
    mysql_comment='help keywords',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'help_keyword', ['name'], unique=True)
    op.create_table('help_category',
    sa.Column('help_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.CHAR(length=64), nullable=False),
    sa.Column('parent_category_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('help_category_id'),
    mysql_comment='help categories',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'help_category', ['name'], unique=True)
    op.create_table('help_relation',
    sa.Column('help_topic_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('help_keyword_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('help_keyword_id', 'help_topic_id'),
    mysql_comment='keyword-topic relation',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('server_cost',
    sa.Column('cost_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('cost_value', mysql.FLOAT(), nullable=True),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('cost_name'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Select_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Insert_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Update_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Delete_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Drop_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Reload_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Shutdown_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Process_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('File_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Grant_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('References_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Index_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_db_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Super_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tmp_table_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Lock_tables_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Execute_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_slave_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Repl_client_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Show_view_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Alter_routine_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_user_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Event_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Trigger_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('Create_tablespace_priv', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('ssl_type', mysql.ENUM('', 'ANY', 'X509', 'SPECIFIED', charset='utf8'), server_default=sa.text("''"), nullable=False),
    sa.Column('ssl_cipher', sa.BLOB(), nullable=False),
    sa.Column('x509_issuer', sa.BLOB(), nullable=False),
    sa.Column('x509_subject', sa.BLOB(), nullable=False),
    sa.Column('max_questions', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_updates', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('max_user_connections', mysql.INTEGER(display_width=11, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('plugin', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("'mysql_native_password'"), nullable=False),
    sa.Column('authentication_string', mysql.TEXT(collation='utf8_bin'), nullable=True),
    sa.Column('password_expired', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.Column('password_last_changed', mysql.TIMESTAMP(), nullable=True),
    sa.Column('password_lifetime', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('account_locked', mysql.ENUM('N', 'Y', charset='utf8'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User'),
    mysql_collate='utf8_bin',
    mysql_comment='Users and global privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('time_zone_leap_second',
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Correction', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Transition_time'),
    mysql_comment='Leap seconds information for time zones',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('proxies_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Proxied_user', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('With_grant', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=93), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'User', 'Proxied_host', 'Proxied_user'),
    mysql_collate='utf8_bin',
    mysql_comment='User proxy privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('procs_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_name', mysql.CHAR(charset='utf8', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Routine_type', mysql.ENUM('FUNCTION', 'PROCEDURE', collation='utf8_bin'), nullable=False),
    sa.Column('Grantor', mysql.CHAR(collation='utf8_bin', length=93), server_default=sa.text("''"), nullable=False),
    sa.Column('Proc_priv', mysql.SET(charset='utf8', length=13), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Routine_name', 'Routine_type'),
    mysql_collate='utf8_bin',
    mysql_comment='Procedure privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('slave_master_info',
    sa.Column('Number_of_lines', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Master_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Master_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Host', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), nullable=True),
    sa.Column('User_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('User_password', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Port', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Connect_retry', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Enabled_ssl', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Ssl_ca', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_capath', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_cert', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_cipher', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_key', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_verify_server_cert', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Heartbeat', mysql.FLOAT(), nullable=False),
    sa.Column('Bind', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ignored_server_ids', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Uuid', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Retry_count', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Ssl_crl', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Ssl_crlpath', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.Column('Enabled_auto_position', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Channel_name', mysql.CHAR(length=64), nullable=False),
    sa.Column('Tls_version', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=True),
    sa.PrimaryKeyConstraint('Channel_name'),
    mysql_comment='Master Information',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_name',
    sa.Column('Name', mysql.CHAR(length=64), nullable=False),
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Name'),
    mysql_comment='Time zone names',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('proc',
    sa.Column('db', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('FUNCTION', 'PROCEDURE'), nullable=False),
    sa.Column('specific_name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('language', mysql.ENUM('SQL'), server_default=sa.text("'SQL'"), nullable=False),
    sa.Column('sql_data_access', mysql.ENUM('CONTAINS_SQL', 'NO_SQL', 'READS_SQL_DATA', 'MODIFIES_SQL_DATA'), server_default=sa.text("'CONTAINS_SQL'"), nullable=False),
    sa.Column('is_deterministic', mysql.ENUM('YES', 'NO'), server_default=sa.text("'NO'"), nullable=False),
    sa.Column('security_type', mysql.ENUM('INVOKER', 'DEFINER'), server_default=sa.text("'DEFINER'"), nullable=False),
    sa.Column('param_list', sa.BLOB(), nullable=False),
    sa.Column('returns', mysql.LONGBLOB(), nullable=False),
    sa.Column('body', mysql.LONGBLOB(), nullable=False),
    sa.Column('definer', mysql.CHAR(charset='utf8', collation='utf8_bin', length=93), server_default=sa.text("''"), nullable=False),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('sql_mode', mysql.SET(length=26), server_default=sa.text("''"), nullable=False),
    sa.Column('comment', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('character_set_client', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('collation_connection', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('db_collation', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('body_utf8', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('db', 'name', 'type'),
    mysql_comment='Stored Procedures',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('innodb_index_stats',
    sa.Column('database_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('table_name', mysql.VARCHAR(collation='utf8_bin', length=199), nullable=False),
    sa.Column('index_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('last_update', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('stat_name', mysql.VARCHAR(collation='utf8_bin', length=64), nullable=False),
    sa.Column('stat_value', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('sample_size', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('stat_description', mysql.VARCHAR(collation='utf8_bin', length=1024), nullable=False),
    sa.PrimaryKeyConstraint('database_name', 'table_name', 'index_name', 'stat_name'),
    mysql_collate='utf8_bin',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('slave_worker_info',
    sa.Column('Id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Relay_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Relay_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Master_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Master_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_relay_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Checkpoint_relay_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_master_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Checkpoint_master_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_seqno', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_group_size', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Checkpoint_group_bitmap', sa.BLOB(), nullable=False),
    sa.Column('Channel_name', mysql.CHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('Channel_name', 'Id'),
    mysql_comment='Worker Information',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('servers',
    sa.Column('Server_name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Host', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Username', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Password', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Port', mysql.INTEGER(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('Socket', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Wrapper', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Owner', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Server_name'),
    mysql_comment='MySQL Foreign Servers table',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('Use_leap_seconds', mysql.ENUM('Y', 'N'), server_default=sa.text("'N'"), nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id'),
    mysql_comment='Time zones',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('func',
    sa.Column('name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('ret', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('dl', mysql.CHAR(collation='utf8_bin', length=128), server_default=sa.text("''"), nullable=False),
    sa.Column('type', mysql.ENUM('function', 'aggregate', charset='utf8'), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_collate='utf8_bin',
    mysql_comment='User defined functions',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('gtid_executed',
    sa.Column('source_uuid', mysql.CHAR(length=36), nullable=False),
    sa.Column('interval_start', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('interval_end', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('source_uuid', 'interval_start'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone_transition',
    sa.Column('Time_zone_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Transition_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Transition_type_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Time_zone_id', 'Transition_time'),
    mysql_comment='Time zone transitions',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('event',
    sa.Column('db', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('name', mysql.CHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('body', mysql.LONGBLOB(), nullable=False),
    sa.Column('definer', mysql.CHAR(charset='utf8', collation='utf8_bin', length=93), server_default=sa.text("''"), nullable=False),
    sa.Column('execute_at', mysql.DATETIME(), nullable=True),
    sa.Column('interval_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('interval_field', mysql.ENUM('YEAR', 'QUARTER', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'WEEK', 'SECOND', 'MICROSECOND', 'YEAR_MONTH', 'DAY_HOUR', 'DAY_MINUTE', 'DAY_SECOND', 'HOUR_MINUTE', 'HOUR_SECOND', 'MINUTE_SECOND', 'DAY_MICROSECOND', 'HOUR_MICROSECOND', 'MINUTE_MICROSECOND', 'SECOND_MICROSECOND'), nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('last_executed', mysql.DATETIME(), nullable=True),
    sa.Column('starts', mysql.DATETIME(), nullable=True),
    sa.Column('ends', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM('ENABLED', 'DISABLED', 'SLAVESIDE_DISABLED'), server_default=sa.text("'ENABLED'"), nullable=False),
    sa.Column('on_completion', mysql.ENUM('DROP', 'PRESERVE'), server_default=sa.text("'DROP'"), nullable=False),
    sa.Column('sql_mode', mysql.SET(length=26), server_default=sa.text("''"), nullable=False),
    sa.Column('comment', mysql.CHAR(charset='utf8', collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('originator', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('time_zone', mysql.CHAR(charset='latin1', length=64), server_default=sa.text("'SYSTEM'"), nullable=False),
    sa.Column('character_set_client', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('collation_connection', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('db_collation', mysql.CHAR(charset='utf8', collation='utf8_bin', length=32), nullable=True),
    sa.Column('body_utf8', mysql.LONGBLOB(), nullable=True),
    sa.PrimaryKeyConstraint('db', 'name'),
    mysql_comment='Events',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_table('slave_relay_log_info',
    sa.Column('Number_of_lines', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Relay_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Relay_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Master_log_name', mysql.TEXT(charset='utf8', collation='utf8_bin'), nullable=False),
    sa.Column('Master_log_pos', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Sql_delay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Number_of_workers', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('Channel_name', mysql.CHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('Channel_name'),
    mysql_comment='Relay Log Information',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('plugin',
    sa.Column('name', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('dl', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    mysql_comment='MySQL plugins',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('columns_priv',
    sa.Column('Host', mysql.CHAR(collation='utf8_bin', length=60), server_default=sa.text("''"), nullable=False),
    sa.Column('Db', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('User', mysql.CHAR(collation='utf8_bin', length=32), server_default=sa.text("''"), nullable=False),
    sa.Column('Table_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Column_name', mysql.CHAR(collation='utf8_bin', length=64), server_default=sa.text("''"), nullable=False),
    sa.Column('Timestamp', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('Column_priv', mysql.SET(charset='utf8', length=10), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'Db', 'User', 'Table_name', 'Column_name'),
    mysql_collate='utf8_bin',
    mysql_comment='Column privileges',
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.drop_table('record')
    op.drop_table('series')
    op.drop_table('recording_parameters')
    op.drop_index(op.f('ix_recorder_uid'), table_name='recorder')
    op.drop_table('recorder')
    op.drop_table('label')
    # ### end Alembic commands ###
